### ISSUE TITLE
Adding this feature to firefox

### ISSUE THREAD

**Issue by rayman89** [jingyu9575/select-after-closing-current#11]
This bug is about adding support to selecting what tab is selected after closing current https://bugzilla.mozilla.org/show_bug.cgi?id=1419947 they are open to users to help with that to add it to firefox.  I was wondering if you were able to colaborate with that.

**Comment by jingyu9575** [comment]
I looked at the Firefox source and it turns out to be more difficult than I thought. 

The proposed method is to add an asynchronous event that blocks the default Firefox closing behavior ([Bug 1419947](https://bugzilla.mozilla.org/show_bug.cgi?id=1419947#c0) (2nd suggestion), [Bug 1422509](https://bugzilla.mozilla.org/show_bug.cgi?id=1422509#c0)). However, the browser immediately requires a tab to activate even before the closing is completed (the function call [`_blurTab`](https://github.com/mozilla/gecko-dev/blob/f7cc5bd6b5c5b059328f1b027d3f41aaa68dd79b/browser/base/content/tabbrowser.js#L2807) and [`_findTabToBlurTo`](https://github.com/mozilla/gecko-dev/blob/f7cc5bd6b5c5b059328f1b027d3f41aaa68dd79b/browser/base/content/tabbrowser.js#L3096)), so adding an blocking event is impossible without changing lots of code.

One possible workaround is adding an API to specify the next tab to select in advance (before the closing), so when the current tab is closed, this tab can be immediately chosen as the result of `_findTabToBlurTo`. This is implemented in [v4.0.1exp](https://github.com/jingyu9575/select-after-closing-current/releases/tag/v4.0.1exp), which can only be installed on Firefox Developer Edition, Nightly or unbranded builds because of privileged code. I am testing this version, and if it is stable and efficient enough, I'll ask if Firefox can accept this API.

**Comment by jingyu9575** [comment]
Another developer ryan.hendrickson is [working on this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1419947#c20) and the solution looks more complete. Let's see if it will be accepted.

**Comment by jingyu9575** [comment]
A new enhancement of WebExtensions API called tab successors just landed in today's Firefox Nightly Build 20181128100125. (Thanks ryan.hendrickson!)

This extension now uses it to prevent the browser's default selection, so flashing, Ctrl+Tab order changes and tab discarding incompatibility are mitigated.

Please comment in #13 if there are issues with this feature.
