### ISSUE TITLE
[Bug] Unable to switch to tab at address bar

### ISSUE THREAD

**Issue by ReporterX** [jingyu9575/select-after-closing-current#16]
Firefox 66.0.3  
Select after closing current 4.1

1. Type any keyword at the address bar which matches the existing tab you have opened
2. Select the tab via the addresss bar (you will see the word "switch to tab") in the address bar's popup menu

Expected: Jump to that tab

Actual: It will jump to that tab and then jump back

**Comment by jingyu9575** [comment]
This is the same issue as #4. Unfortunately it is still not fixed by Firefox, and I'm not aware of any solution apart from that workaround.

**Comment by jingyu9575** [comment]
On second thought, this probably can be fixed on Firefox 65+, by disabling the old method for Firefox 64- and only use the new method (#13). 

If you are using the built-in about:newtab new tab page, please turn on the option "Disable if the closed tab is a newly created about:newtab" and see whether the bug still happens, and whether the extension still works.

**Comment by ReporterX** [comment]
Yep it is largely fixed. I tried about 7-9 times but failed one time. I tried again but it succeeded so I'm not sure how exactly that failure happened to reproduce it.

I will inform you if I spotted the exact pattern. Thank you.

**Comment by jingyu9575** [comment]
I've updated this option to account for non-default new tab page, and fixed some problems. Since it can fix this bug without compromising functionality now, the option is renamed to "Fix incompatibility with switching to tab from the address bar", and enabled by default for new installs.

@ReporterX If the latest version v4.2 still has failures, feel free to reopen this bug.
