### ISSUE TITLE
[Feature Request] Select after Unload, too

### ISSUE THREAD

**Issue by TheUnloader** [jingyu9575/select-after-closing-current#17]
When I unload/discard a tab, then it would be great to have the same behavior like when I close a tab. I wonder, nobody before me requested this already.

I'm using the addon "Tree Style Tab" with addon "Tab Unloader for Tree Style Tab", which have configured to use addon "Auto Tab Discard".

I wished that the rules I have set for closing a tab would apply to unloading/discarding, too.

**Comment by jingyu9575** [comment]
Tab unloading behaves differently from closing in Firefox. It is possible to close the current tab and extensions see events in this order:

1. Close current tab
2. Auto-select the right tab

and my extension can inject a different selection between the events.

However, it is not possible to unload the current tab. You can see this with [another extension](https://addons.mozilla.org/firefox/addon/discard-tab). "Tab Unloader for Tree Style Tab" workarounds this limitation, by [selecting another tab](https://github.com/Lej77/tab-unloader-for-tree-style-tab/blob/57d55ac017307f1e13a46abc4c58faf6a98e20bd/background.js#L113) before unloading. Therefore my extension see these events:

1. Select a tab
2. Unload the previously active tab

which cannot be distinguished from two separate user actions, and my extension cannot act on this reliably.

In this situation, the selected tab can only be determined by the unloading extension "Tab Unloader for Tree Style Tab". It already has an option now:

> * [x] Select last focused: If tab is active then select the last focused tab. If this is not checked then the closest tab is selected.

If you want different behavior (instead of last focused or closest), it probably needs cooperation with that extension's developer.

**Comment by TheUnloader** [comment]
Thank you very much for your detailed explanation and for pointing me to the option "Select last focused". For now it is pretty much what I needed when unloading tabs! 👍  I guess, I will (try to) close this issue then.
