### ISSUE TITLE
ACTIVE PINNED TAB JUMPED

### ISSUE THREAD

**Issue by EstherMoellman** [jingyu9575/select-after-closing-current#18]
Hi @jingyu9575 !

I'm using latest FF Nightly. Since several weeks I'm seeing a change in pinned tabs.

First, I must start saying that I use "manager or grouping tab add-ons" (like SimpleTabGroups or PowerTabs etc). These tab-manager-add-ons basically group tabs, hiding and discarding (unloading) tabs when jumping from one group to another. But normally, these add-ons only work/deal with unpinned tabs. So, pinned tabs always are autonomous and ungrouped.

In this context, for months your add-on SelectAfterClosingCurrent (SACC) worked like a charm: If my active/selected tab was a pinned one, your add-on ensured that this active pinned remained in focus even when jumping from a tab group to another.

Sadly, since a couple of weeks, this behavior changed: Now when I jump from one group to another, if the active tab is a pinned one, then it is ignored, and the last unpinned active tab is opened in the new group. In simple words: When a tab group is changed, pinned tabs are not recognized as active/selected, and the last active tab in this group is selected (even if was not the last active tab, or was unloaded, discarded, unfocused etc).

I tried to play with SACC' settings changing and testing different setting combinations... but I haven't seen changes at all. So, it will be great if SACC incorporates an option, allowing the user to choice if pinned tabs should remain (or not) considered as "active/selected/focused tab" (in my case, I love the original default option: To always keep a pinned tab as focused, if it was active/selected etc).

Thanks!

**Comment by jingyu9575** [comment]
With some preliminary testing, I reached the same conclusion as you: it may be a [issue of SimpleTabGroups](https://github.com/Drive4ik/simple-tab-groups/issues/433).

Please disable my extension and see what happens. If the same happens, it should be an issue of the other extension.

**Comment by EstherMoellman** [comment]
> 
> 
> With some preliminary testing, I reached the same conclusion as you: it may be a [issue of SimpleTabGroups](https://github.com/Drive4ik/simple-tab-groups/issues/433).
> 
> Please disable my extension and see what happens. If the same happens, it should be an issue of the other extension.

@jingyu9575  first, thanks for your prompt answer (as usual). You always are very responsive. Thanks!

Yeah, I recognize you it might be a STG (SimpleTabGroups) or FF Nightly' issue, and because of this, just in case yesterday I opened an issue at STG (asking the Dev to try to find a solution).

However, today I also opened an issue here because in the past, when I started to use tab-manager-add-ons (PowerTabs), just by using your add-on (SACC) that I was able to have the function of keeping a pinned tab focused even when a tab group is jumped. What I am trying to say is that I am not really sure what is the cause of the issue: Your add-on? Tab-manager-add-ons? FF Nightly?

If in the past your add-on did the trick for me, and my guess today was that your add-on might make the trick again now. That's the reason I opened the issue here.

Thank you anyway!

**Comment by jingyu9575** [comment]
> what is the cause of the issue

Tab manager extensions are built upon the tab hiding feature. When switching tab groups, all the target group's tabs are unhidden, and all the original group's tabs are hidden.

Firefox does not allow hiding or discarding the active tab, so tab manager extensions use careful command sequences to avoid this. For example, suppose the current tab group is:
```
[A][    B    ]
```
A is pinned, while B is active. The user wants to switch to another group:
```
[A][    C    ]
```
Firefox's restriction means hiding the active tab B will do nothing, so tab managers figure out C should be the next active tab, and send the following commands: `Unhide C; Switch to C; Hide B`. 

Then what if A is active and the user switches? Tab managers can do one of the followings:

1. Figure out C should be the next active tab.
    `Unhide C; Switch to C; Hide B`
2. Figure out A should remain active. (This is what you want.)
    `Unhide C; Hide B`

The only difference is whether the tab manager decide to switch active tab as the 2nd command. SimpleTabGroups v3 choose behavior 2, but v4 choose behavior 1 for now. The next version will [revert to behavior 2](https://github.com/Drive4ik/simple-tab-groups/commit/76eee8e3558b07250193adca53fb8608940f37d2), fixing your issue.

---

> in the past your add-on did the trick

My extension only runs code when the active tab is closed or detached. For this case, no tab is closed or detached, and no current tab is hidden (because of Firefox's restriction), so my extension should not do anything.

During my testing, PowerTabs chooses behavior 1 or 2 depending on which group is being activated, and my extension has no effects. 

---

I do not think my extension can implement any workaround. The tab manager must choose behavior 2 to begin with. Fortunately this will be the case for the next verison of STG.

**Comment by EstherMoellman** [comment]
@jingyu9575 ... what a nice explanation!... THANK YOU!
Yeah, the STG' Dev answer me after I wrote you. So based on his answer to me, now is clear that this "pinned tab issue" happened due to STG' code changes. But your explanation was very useful, so thank you anyway.

I still wonder how I made the "pinned tab" work before STG and with your add-on. After your explanation, I can see now that was just my imagination (ignorance), and your add-on had nothing to do with it.

But in any case, and as I wrote you in my previous comment, based on my ignorance, I still believe it will be nice to have an option in your add-on, allowing the user to choose a pinned tab, as "select after closing current". Again, it might be just an user option! Not to choose the first, right, left or last tab, but to choose always a pinned tab. The rational behind that is not related to tab-manager-add-ons. To choose always a pinned tab is very useful for users (like me) that have tons of tabs. For example, normally all my tabs are discarded/unloaded (and hidden by STG), and when I want to see a group of tabs or bookmarks, not necessarily I want the first, last, right or left active tab... sometimes I am just interested in another tab in this group... so, by always having a pinned tab as selected (I have an empty blank pinned tab), this simple trick allows me to have a group of tabs or bookmarks unloaded, and I can decide which tab will be active from this group. Please, consider this just a suggestion. 

Another different suggestion for your add-on, is to refresh/reload the chosen active tab. For example, let's suppose an user wants the left tab to be "select after closing current". But this left tab is unloaded/discarded. It will be nice if your add-on can automatically refresh/reload this left tab, not just make it active again, but reload it from the scratch (so the tab can load the latest content). REDDIT is an example where discarded tabs always need to be refreshed if users want to see new posts, comments, latest stuff etc.

Thank you once again! 
Have a nice weekend :)

**Comment by jingyu9575** [comment]
> have an option in your add-on, allowing the user to choose a pinned tab

I think it is not difficult, but isn't the pinned tab just the first tab? Are you occasionly use the pinned tab, and sometimes do not use, and want the extension to differenciate the two cases (e.g. has pinned tab: switch to it; doesn't have pinned tab: switch to last accessed tab)?

> discarded tabs always need to be refreshed

Try [Update Discarded Tab On Select](https://addons.mozilla.org/firefox/addon/update-discarded-tab-on-select/). I think it is not a good idea to integrate this function into mine, because the reloading of discarded tab should be consistent (no matter how it is activated), rather than only works when activating after closing another tab.

**Comment by EstherMoellman** [comment]
Hi @jingyu9575 ! 

I have no idea if technically Firefox can differentiate "first tab" from "pinned tab". But for sure they are two different things, at least from my intuitive user point of view. Based on my ignorance, the "first tab" should be the first unpinned tab. And if your add-on allows to choose "first", "last", "right" and "left" tab... then why not to add an option for "pinned" tab? Seems to me to complement the logic of your add-on.

Now and with regards to your question about "pinned tab use", in my ignorant opinion it will be nice if your add-on can:
1) To differentiate the two cases you stated
2) But also to have an additional option to always force pinned tab as "last accessed tab", regardless and ignoring the real last accessed tab.
Please, if possible, the two options above will be great! It will make your add-on more and more interesting, and also more useful for different user profiles.

Yeah, I already use the add-on you mentioned for refreshing discarded tabs. And I understand your answer, from your Dev' point of view. However, user point of view (wrong most of the time) wants to have the less number of add-ons possible (this is my case): It might reduce conflicts, improve browser performance, security and privacy etc... I believe that the less the better. That's the reason I asked you to include this function to your add-on. And it makes sense! It is logic! If your add-on always go the last accessed tab, and this tab is discarded/unloaded, then why not to offer an option where the user may refresh discarded tabs? Again, it seems to me logic, it might make your add-on more and more interesting and useful for different user profiles.
I hope this will be doable and you will accept my suggestion.

@jingyu9575  tons of thanks to you for your time, patience, responsiveness, and for your willing to hear suggestions.

Big hug! :)

**Comment by jingyu9575** [comment]
> pinned tab

Added in 4.3. For your second point, I think the configuration should be:

![configuration](https://user-images.githubusercontent.com/8923139/62824032-a35bc880-bbca-11e9-9491-3b686c152494.png)

> refreshing discarded tabs

I've tried to implement this, but failed because Firefox's strange behavior. Suppose the tabs are:
```
[A (discarded) ][ B (active) ]
```
When B is closed, Firefox is giving the events in this strange order:

1. A is no longer discarded
2. B is closed --> This is when my extension does the work
3. A is active

Therefore, when the extension makes the decision, A is already reported as non-discarded, and there is no reliable way to address this issue.

> user point of view [...] wants to have the less number of add-ons possible

Well as a dev I think "separation of concerns" is also important, i.e. keep one feature in one extension and move other features into separate programs. This way, when one feature has issues, only this part needs to be checked and fixed.

Think about this: the extension Update Discarded Tab On Select requires (and actually needs) the permission ["Access your data for all websites"](https://www.jeffersonscher.com/sumo/extensions.php#sort=created,guid=%7Bda80c0e7-d276-47f7-a0ca-7c8d6126bd81%7D). If I merge the feature into my extension, it will need this permission as well, which [isn't preferred](https://addons.mozilla.org/zh-CN/firefox/addon/multithreaded-download-manager/reviews/1398465/) by many users. 

I don't think the two extension conflicts or causes significant performance drops. However, I think security is a real problem: more extensions mean more attack surfaces if any of our developer account got hacked. Unfortuantely I'm not aware of solutions for this.

**Comment by EstherMoellman** [comment]
@jingyu9575 ... thanks for the upgrade!... cool!... very nice.
 谢谢 xiè xiè... hope I'm writing in the right way :)  

I understand that "reload discarded tab" will be a "no go" this time. And again, I also perfectly understand your Dev' point of view. But the sample you posted (with another user complaining about your add-on and "access all data") is a selective sample. Let's take our case, with you recommending me the other reload-discarded-tab extension... it happens that your add-on is an OPEN SOURCE (and the other add-on you recommended me is not)... and I always will prefer to allow "access all data" to your OPEN SOURCE add-on... and I am sure that most of the users will have the same preferences I have.
In addition, it is always preferred to reduce the number of add-ons (this avoids conflicts, improves browser performance etc). I'm sure you know that.
I don't believe users will choose an add-on, just because it doesn't needs "access all data". In my case, always I will choose an add-on taking into account: a) Open Source b) Browser performance. If the chosen add-on satisfies "a)" + "b)", then in my opinion the "access all data" is secondary.
I may agree with you (to keep the original add-on functions), if an user suggests a very weird request. But let's agree that "to refresh a tab" with your add-on, is a very common-sense suggestion/request.
So who knows, hope never dies (LOL), perhaps in the future you find a way to include "refresh tab" to your add-on. 

Anyway, I'm totally satisfied with your upgrade, and you deserve zillions of "thank you", zillions of  谢谢 :)

Cheers

**Comment by jingyu9575** [comment]
> users will choose an add-on, just because it doesn't needs "access all data"

See what happens when another extension [reload in address bar](https://addons.mozilla.org/firefox/addon/reload-in-address-bar/) decided to add this permission for a new feature: 4 angry reviews [[1](https://addons.mozilla.org/en-US/firefox/addon/reload-in-address-bar/reviews/1198593/),[2](https://addons.mozilla.org/en-US/firefox/addon/reload-in-address-bar/reviews/1198438/),[3](https://addons.mozilla.org/en-US/firefox/addon/reload-in-address-bar/reviews/1198354/),[4](https://addons.mozilla.org/en-US/firefox/addon/reload-in-address-bar/reviews/1198238/)] in one day before the developer was forced to revert the update.

The permission system is causing lots of confusions among users. Even uBlock Origin is [getting questioned](https://github.com/gorhill/uBlock/wiki/Can-you-trust-uBlock-Origin%3F) when adding new permissions.

> your add-on is an OPEN SOURCE (and the other add-on you recommended me is not)

That one is open source; the license is "Mozilla Public License, version 2.0" (MPL).
![Image](https://user-images.githubusercontent.com/8923139/62836811-ba1d2080-bc99-11e9-987c-65970efe4e16.png)
Whether a program is free software (=open source) is determined by the license. Many extensions use MPL, which allows anyone to see, modify, and redistribute the source, with requirements that modified files in MPL must remains in MPL.
![Screenshot](https://user-images.githubusercontent.com/8923139/62836647-f18acd80-bc97-11e9-8578-b85ef2fe3a65.png)
That extension's source can be viewed by simply extracting it, although lacking of GitHub repo makes it difficult to report bugs.

**Comment by EstherMoellman** [comment]
Hi @jingyu9575 ! Thank you for sharing with me your thoughts. I partially disagree (a bit) with you, but I perfectly understand your Dev' point of view, and I do recognize that most of your arguments are totally true.  

However and changing subject, please allow me to take advantage of this contact, to challenge you to build a new add-on... a TAB-GROUPS add-on (TGAD). Most of the existent TGAD are very buggy, in part due to conflicts with new Firefox' functions (FPI First-party-isolation, Containers, Content-blocking, Fission etc), and in part also due to conflicts with other add-ons (specially ad-blockers, tracking-blockers, add-ons dealing with tabs, your add-on etc). But this happens with TGAD mainly because of the use an abuse of hiding/discarding-tabs. With time, most of the TGAD-data become corrupted.
So, what's the idea to build a new TGAD? Simple! Not to use hiding nor discarding, but to deal with tabs as bookmarks.

Here is a good example of what I am talking about:  https://addons.mozilla.org/en-US/firefox/addon/tab-group-switch/
Yeah, this add-on is very imperfect, and even, I can't use it because changes the order of the tabs (while loading them). But this add-on is a prove that a new kind of TGAD is perfectly doable. Sadly there are not TGAD like that. And even bookmark-manager or session-manager add-ons are very bad. I tested almost 20 of them.
So, conclusion, there is a huge niche of users for this kind of TGAD, dealing with tabs as bookmarks, without hiding/discarding tabs. The advantages of this TGAD will be: a) Less conflicts with Firefox' functions, b) Less conflicts with other add-ons, c) Huge browser performance improvement.

If by chance you are interested in this challenge (and I offer you all my help), here below you have more details about this possible new TGAD: 

1) Automatically "convert" visible tabs (in a window) into bookmarks, but saved inside a defined group. The order of the tabs should be preserved.

2) A toolbar button is required, allowing to jump from one group to another group, and also allowing to edit groups.

3) When a group is selected (from the toolbar button), the visible group must close (auto-saving all tabs and preserving tab order), switching and showing the chosen group, but loading (selecting) only the last active tab (it will be great an option allowing to choose which tab must be loaded: first, last, right, left or a pinned tab. Perhaps you code may be useful here?).

PS1: When a group closes, tabs must be closed (not just be hidden, nor discarded). Also, when a tab is loaded, must be reloaded/refreshed.

PS2: It will be a fantastic plus, if tabs can be automatically opened in separated temporary containers.

4) The add-on must be lightweight (around 50kb ~ 500kb) and easy on CPU, RAM etc. No fancy stuff is needed! The less the better.

5) Not a must, but another plus will be: a) Dark Theme b) Back Up c) Open another tab when last active tab is closed d) Open source etc.

It will be fantastic if you are interested. And again, I offer you my help: We are a small "club" of university students (around 150 members in 8 different countries), using FF' Nightly with special CSS customizations, hacks etc. I offer you the help of these 150 students (including me) in order to test your add-ons, or to do other tests, researches etc... whatever we can help, I offer you.   

But, if you don't like the challenge, or don't have time etc, don't worry at all, it is perfectly OK, I understand... we always will love you! (LOL) :)

Big hug

**Comment by jingyu9575** [comment]
@EstherMoellman Please continue [here](https://github.com/jingyu9575/general-offtopic/issues/1), since it is not about features of this extenison.
