### ISSUE TITLE
documentation of features?

### ISSUE THREAD

**Issue by corobin** [jingyu9575/select-after-closing-current#21]
hi i was wondering is there a documentation of the features? I checked the readme and wiki and don't seem to have it.

specifically i'm wondering what these new position options mean: left adjacent, right adjacent

and also what each of the options under the compatibility operating mode means: Mixed, v4, v1

thanks!

**Comment by jingyu9575** [comment]
I've written some explanations here: https://github.com/jingyu9575/select-after-closing-current/wiki/Options

**Comment by sergeevabc** [comment]
@jingyu9575, consider adding a page dedicated to the best practices (since the addon lacks presets except for default one), because there are _too many options_ and it is not obvious, even with explanations you've provided, how to set it all up. For example, I played with it for an hour and was not satistified with the results.
