### ISSUE TITLE
Auto-closed tabs shouldn't trigger focus behaviour

### ISSUE THREAD

**Issue by psmears** [jingyu9575/select-after-closing-current#4]
This extension is great and will hopefully save me from a lot of confusion, but I'm currently hitting one small snag:

I commonly use the following method to select an existing tab from the keyboard:

   1. Press Ctrl+T (opens a new tab and focusses the URL bar)
   2. Type some characters in the title/URL of the tab I want
   3. Firefox drops down a menu of tabs/links
   4. I select the one I want with the arrow keys, and hit Enter
   5. Firefox selects the tab I want
   6. The new, empty tab auto-closes

Unfortunately, the auto-close triggers this extension to focus the tab to the left of the blank tab, which is the tab I started on - so I end up not selecting the tab I want.

Is it possible to disable the select-after-closing-current behaviour for auto-closed tabs?

**Comment by jingyu9575** [comment]
It is because of Firefox's [Bug 1405262](https://bugzilla.mozilla.org/show_bug.cgi?id=1405262). Basically during the switch from the URL bar, extensions see events as if the current tab is closed and the target tab is set as the next activated tab.

When closing the current tab, extensions sees:
* tabs.onRemoved for the current tab
* tabs.onActivated for the default activated tab, usually the right tab or the parent tab

When switching to a tab from the URL bar, extensions sees:
* tabs.onRemoved for the current tab
* tabs.onActivated for the target tab

Therefore extensions cannot tell the two situations apart. This Firefox Bug is still in the "design-decision-needed" phase with low priority, and I do not think the extension can fix it ([see the related Tree Style Tab issue](https://github.com/piroor/treestyletab/issues/1409)). 

I think the only viable workaround now is some heuristics like "if a newly created tab with url `about:newtab` is closed, disable the extension once". Do you want it to be implemented?

**Comment by psmears** [comment]
Ah, I see - I suspected it might be something like that!

If you could implement a workaround like what you suggest, that would be fantastic, yes please :-)

**Comment by jingyu9575** [comment]
The workaround option is added to v2.0. Please leave the issue open to track the status of the upstream bug.

**Comment by psmears** [comment]
This is great - thanks very much :-)

**Comment by jingyu9575** [comment]
It is found that the workaround option can fix this problem without disabling any functionality on Firefox 65+, thanks to the new API #13. 

The option is renamed to "Fix incompatibility with switching to tab from the address bar", and enabled by default for new installs.
