### ISSUE TITLE
Firefox 61 broke the addon

### ISSUE THREAD

**Issue by rayman89** [jingyu9575/select-after-closing-current#8]
It's not working anymore on firefox 61

**Comment by jingyu9575** [comment]
I did not see any problems on Firefox Developer Edition 61.0b1.
Is it having no effect at all, or it has incorrect behavior? Could you provide some steps to reproduce?

**Comment by rayman89** [comment]
when you close current tab I have it set up to select left tab first right tab second but now when closing current tab firefox focuses the last tab on the window.

**Comment by jingyu9575** [comment]
I cannot reproduce it with version 2.0.1, on Firefox Developer Edition 61.0b2, on either Windows or Linux. The left tab is successfully selected. 
Please open about:debugging, check the "Enable Debugging" checkbox, and click "debug" on this extension. Try open and close some tabs. Are there any error messages in the debugger's "Console" tab?
Also, can you reproduce this problem on a new profile?

**Comment by rayman89** [comment]
I tested and it seems like the issue was a profile corruption of the config file of your addon because once I deleted your config file on the profile folder and configured the addon again it started working. Recently I've been having problems with profile corruption after updates. Is this "normal"? Would creating a new profile from scratch prevent it from corruption or something?

**Comment by jingyu9575** [comment]
I have never seen such corruption. In [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1415792), there seem to be some users who are affected by extension data loss, but the reason is unknown. Firefox is working on a top-priority bug to [move the data to indexedDB](https://bugzilla.mozilla.org/show_bug.cgi?id=1406181) (the browser's database storage), which hopefully can solve this problem.
I am not sure whether creating a new profile can help. I suggest making backups of the current profile, so it is easy to restore in case it breaks again.

**Comment by d4k0** [comment]
I'm not sure, but I also got some strange behaviour that started with Firefox 61 (final version). The add-on is set to right tab, left tab and then last accessed tab, but sometimes the left tab is selected (it could also be the last accessed tab) even though there are tabs to the right. Sometimes it even jumps over a few right tabs (could be the right sibling tab that is selected), but so far I couldn't make out a pattern. With previous versions of Firefox the add-on worked without a problem.

I already tried to remove (and reinstall) the add-on and all its settings from the profile folder, but the problem is still there. Starting with Firefox 61 I set `browser.tabs.insertAfterCurrent` to true (before that I used the add-on "Always Right" to open all tabs to the right) which seems to be the only new setting that affects tab handling.

I will probably now set the add-on to right tab only and see how it behaves. Is the Firefox Developer Edition the only way to debug the add-on?

**Comment by jingyu9575** [comment]
@d4k0 I still cannot reproduce the issue on Firefox 61.0.1, with your settings and `browser.tabs.insertAfterCurrent` on.

There are some event loggings in the extension, which are turned off by default. To see them, Open `about:debugging#addons`, check the "Enable add-on debugging" checkbox, and click the "Debug" button next to this extension. In the "Console" tab, click the trash icon to clear, and then run `DEBUG=true` in the command bar at the bottom. The tab events will show in the console. Watch if there are errors or incorrect decisions.

Firefox Developer Edition allows unsigned extensions (that has not been screened by Mozilla's automatic check), so it is useful to extension developers who need to test unfinished extensions. For signed extensions from Mozilla's addons site, there is no difference except for the version.

**Comment by d4k0** [comment]
Thanks for your answer. It seems to have worked today, but I will activate the logging if it appears again.

Interesting that you now also see some errors.

**Comment by d4k0** [comment]
I activated the logging today. This is what I get when the add-on selects the correct tab:

```
tabs.onRemoved 2183 background.js:272:13
selected 1404 background.js:196:15
tabs.onActivated 1404 background.js:241:13
unfreezeWindow 1404 background.js:105:13
Error: "inconsistent index of 1381"
     checkConsistency moz-extension://dffe11b2-5fd0-4fef-8e11-858f98303d02/background.js:78:12 background.js:90:19
checkConsistency/< moz-extension://dffe11b2-5fd0-4fef-8e11-858f98303d02/background.js:90:19
```

This is how the log looks when the wrong tab is selected (in this case it was the left tab instead of the right):

```
tabs.onRemoved 1404 background.js:272:13
selected 1381 background.js:196:15
tabs.onActivated 1382 background.js:241:13
tabs.onActivated 1381 background.js:241:13
unfreezeWindow 1381 background.js:105:13
Error: "inconsistent index of 1381"
     checkConsistency moz-extension://dffe11b2-5fd0-4fef-8e11-858f98303d02/background.js:78:12 background.js:90:19
checkConsistency/< moz-extension://dffe11b2-5fd0-4fef-8e11-858f98303d02/background.js:90:19
```

The only difference is `selected 1381 background.js:196:15` in the second line when the wrong tab is selected.

One strange is that I **always** get `Error: "inconsistent index of 1381"` when a tab is closed (or restored). The index seems to stay the same and it also the index that is displayed in line 2 when the wrong tab is selected.

**Comment by jingyu9575** [comment]
Thanks for the log.

It is found that when using the "Undo Close Tab" feature, sometimes Firefox sends tab events in an unexpected order, causing this extension to fail. Now the extension (v3.1) can defend against this.

### Details:

Firefox runs extension code in a separate process (the out-of-process extensions feature), while the tab information resides in the main process. Getting tab information requires asynchronous calls and it is too slow if the extension does this every time a current tab closes. Therefore, the extension listens to tab events, and rebuilds/maintains a local copy of the tab data.

When `DEBUG=true` the extension validates the local data on every events. "Inconsistent index of 1381" means the tab 1381 has different indexes (positions) in the local data and the main process. In the second log, the actual tab order was `1381 [1404] 1382`, but the extension's local data might be `[1404] 1381 1382`, so it made the decision to activate 1381, actually the left tab.

The reason of the inconsistent order happens earlier and is not clear from the logs. During testing I found that when using the "Undo Close Tab" feature, Firefox 61 and 62 sometimes send tab events in the following order:

> tabs.onMoved 100
> tabs.onCreated 100
> tabs.onActivated 100

First a non-existent tab is moved, and then it is created and activated. The extension did not expect this and would create an additional tab 100 on the `onCreated ` event, corrupting the index (position) of the tabs on the right.

Now if a tab id does not exist in the local data, the extension will ignore its `onMoved` event.
